server:
  port: 18888


spring:
  application:
    name: password
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxxxxx:3306/password?characterEncoding=utf-8
    username: xxxxxx
    password: xxxxxx

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

mybatis:
  type-aliases-package: cn.cmw.pass.entity
  mapper-locations: classpath:cn/cmw/pass/mapper/*.xml
  check-config-location: true
